# Exercise 4.3
## Classification
In the following tasks, we will repeatedly use some basic functions (e.g., the softmax function or the cross-entropy) of the [Keras](https://keras.io/) Library. To familiarize with them, we will implement the most important of them ourselves in this task.

Suppose we want to classify some data (4 samples) into 3 distinct classes: 0, 1, and 2.
We have set up a network with a pre-activation output `z` in the last layer.
Applying softmax will give the final model output.

input X ---> some network --> `z`<br>
--> `y_model = softmax(z)`

We quantify the agreement between truth (y) and model using categorical cross-entropy.

$$J = - \sum_i (y_i * \log(y_\mathrm{model}(x_i))$$

In the following you are to implement softmax and categorical cross-entropy
and evaluate them values given the values for `z`.

In [1]:
import numpy as np

##### Data: 4 samples with the following class labels (input features X irrelevant here)

In [7]:
y_cl = np.array([0, 0, 2, 1])
y_cl

array([0, 0, 2, 1])

##### output of the last network layer before applying softmax

In [3]:
z = np.array([
    [4,    5,    1],
    [-1,  -2,   -3],
    [0.1, 0.2, 0.3],
    [-1,  17,    1]
    ]).astype(np.float32)

## Task 1)
Write a function that turns any class labels `y_cl` into one-hot encodings `y`.

0 --> (1, 0, 0)<br>   
1 --> (0, 1, 0)<br>   
2 --> (0, 0, 1)<br>

Make sure that `np.shape(y) = (4, 3)` for `np.shape(y_cl) = (4)`.



In [18]:
def one_hot_encod(y_cl):
    y=[]
    for lab in y_cl:
        y_lab=np.array([0,0,0])
        y_lab[lab]=1
        y.append(y_lab)
    return np.array(y)

y_encod=one_hot_encod(y_cl)
print(y_encod)
np.shape(y_encod)

[[1 0 0]
 [1 0 0]
 [0 0 1]
 [0 1 0]]


(4, 3)

## Task 2)
Write a function that returns the softmax of the input `z` along the last axis

In [32]:
def softmax(z):
    z_exp=np.exp(z).T
    norm=np.sum(z_exp,axis=0)
    return (z_exp/norm).T

softmax(z)

array([[2.6538792e-01, 7.2139925e-01, 1.3212887e-02],
       [6.6524100e-01, 2.4472848e-01, 9.0030573e-02],
       [3.0060962e-01, 3.3222499e-01, 3.6716542e-01],
       [1.5229979e-08, 9.9999994e-01, 1.1253517e-07]], dtype=float32)

## Task 3)
Compute the categorical cross-entropy between data and model

In [36]:
def cross_entropy(y,z):
    #z=f_model(x)
    return -np.mean(np.sum(y * np.log(z), axis=1))

cross_entropy(y_encod,softmax(z))

0.684027835726738

## Task 4)
Determine which classes are predicted by the model (maximum prediction)

In [39]:
y_model_cl = np.argmax(z, axis=1) #predicted labels
print(y_model_cl)
print("real labels "+str(y_cl))

[1 0 2 1]
real labels [0 0 2 1]


## Task 5)
Estimate how many samples are classified correctly (accuracy)

In [42]:
accuracy = np.mean(y_model_cl == y_cl)
print(accuracy)
#only the first is wrong
y_model_cl == y_cl

0.75


array([False,  True,  True,  True])